### ISSUE TITLE
Unexpected permission denied error

### ISSUE THREAD

**Issue by pluser** [pluser/fusebox#10]
In the Fusebox, `ebuild hello-2.10-r1.ebuild unpack`:

```
>>> Not marked as unpacked; recreating WORKDIR...
[Errno 13] Permission denied: b'/bin/bash':
   /bin/bash -c >> /var/cache/distfiles/.__portage_test_write__ 2>/dev/null ; rval=$? ; rm -f  /var/cache/distfiles/.__portage_test_write__ ; exit $rval
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/portage/process.py", line 391, in spawn
  File "/usr/lib64/python3.6/site-packages/portage/process.py", line 752, in _exec
  File "/usr/lib64/python3.6/site-packages/portage/__init__.py", line 246, in __call__
PermissionError: [Errno 13] Permission denied: b'/bin/bash'
!!! Permission Denied: /var/lib/layman/wjn-overlay/profiles/thirdpartymirrors
```

I checked whether the file is able to open.

```
cat /bin/bash > /dev/null  # no error. it can be opened.
cat /var/lib/layman/wjn-overlay/profiles/thirdpartymirrors > /dev/null  # no error. it can be opened.
```

I tried trace by `strace -f ebuild hello-2.10-r1.ebuild unpack`.

```
<...snip...>
[pid 588843] clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 588845 attached
, child_tidptr=0x7f6ec65b3a10) = 588845
[pid 588845] set_robust_list(0x7f6ec65b3a20, 24) = 0
[pid 588843] wait4(588845,  <unfinished ...>
[pid 588845] getpid()                   = 588845
[pid 588845] rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, 8) = 0
[pid 588845] rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, 8) = 0
[pid 588845] rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, 8) = 0
[pid 588845] rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, 8) = 0
[pid 588845] rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f6ec67549a0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
[pid 588845] ioctl(1, FIONCLEX)         = 0
[pid 588845] dup2(1, 2)                 = 2
[pid 588845] fcntl(1, F_GETFD)          = 0
[pid 588845] fcntl(2, F_SETFD, 0)       = 0
[pid 588845] ioctl(0, FIONCLEX)         = 0
[pid 588845] setgid(250)                = 0
[pid 588845] setgroups(1, [250])        = 0
[pid 588845] setuid(250)                = 0
[pid 588845] umask(002)                 = 022
[pid 588845] execve("/bin/bash", ["bash", "-c", ">> /var/cache/distfiles/.__porta"...], 0x56099864f610 /* 207 vars */) = -1 EACCES (Permission denied)
[pid 588845] write(2, "[Errno 13] Permission denied: b'"..., 197[Errno 13] Permission denied: b'/bin/bash':
   /bin/bash -c >> /var/cache/distfiles/.__portage_test_write__ 2>/dev/null ; rval=$? ; rm -f  /var/cache/distfiles/.__portage_test_write__ ; exit $rval
) = 197
[pid 588845] stat("/usr/lib64/python3.6/site-packages/portage/process.py", 0x7ffeaf408870) = -1 EACCES (Permission denied)
[pid 588845] openat(AT_FDCWD, "/usr/lib64/python3.6/site-packages/portage/process.py", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
[pid 588845] stat("/usr/lib64/python3.6/site-packages/portage/process.py", 0x7ffeaf408870) = -1 EACCES (Permission denied)
[pid 588845] openat(AT_FDCWD, "/usr/lib64/python3.6/site-packages/portage/process.py", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
[pid 588845] stat("/usr/lib64/python3.6/site-packages/portage/__init__.py", 0x7ffeaf408870) = -1 EACCES (Permission denied)
[pid 588845] openat(AT_FDCWD, "/usr/lib64/python3.6/site-packages/portage/__init__.py", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
[pid 588845] write(2, "Traceback (most recent call last"..., 35Traceback (most recent call last):
) = 35
[pid 588845] write(2, "  File \"/usr/lib64/python3.6/sit"..., 83  File "/usr/lib64/python3.6/site-packages/portage/process.py", line 391, in spawn
) = 83
[pid 588845] write(2, "  File \"/usr/lib64/python3.6/sit"..., 83  File "/usr/lib64/python3.6/site-packages/portage/process.py", line 752, in _exec
) = 83
[pid 588845] write(2, "  File \"/usr/lib64/python3.6/sit"..., 87  File "/usr/lib64/python3.6/site-packages/portage/__init__.py", line 246, in __call__
) = 87
[pid 588845] write(2, "PermissionError: [Errno 13] Perm"..., 60PermissionError: [Errno 13] Permission denied: b'/bin/bash'
) = 60
[pid 588845] exit_group(1)              = ?
[pid 588845] +++ exited with 1 +++
<...snip...>
```

Hmm?

**Comment by pluser** [comment]
pyfuse3/libfuse refused access from non-owner.
Grant access to non-owner will resolve this problem. Thanks for your hint!!
