### ISSUE TITLE
^c does not terminate gracefully

### ISSUE THREAD

**Issue by mgorny** [pluser/fusebox#2]
```
^CTraceback (most recent call last):
  File "fusebox.py", line 449, in main
    trio.run(start, args.mountpoint)
  File "/home/mgorny/git/fusebox/.venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File "fusebox.py", line 413, in start
    nursery.start_soon(pyfuse3.main)
  File "/home/mgorny/git/fusebox/.venv/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/mgorny/git/fusebox/.venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1107, in raise_cancel
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fusebox.py", line 458, in <module>
    main()
  File "fusebox.py", line 452, in main
    raise RuntimeError
RuntimeError
```

I suppose you need to handle `KeyboardInterrupt` somewhere. Otherwise, the mount point stays broken.

**Comment by pluser** [comment]
Thank you for the advice.
It was fixed at https://github.com/pluser/fusebox/commit/691ebeb2aedf9ab3b9c9c568955c22e203926a42 .
